# Generated by Django 3.1.2 on 2020-10-28 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('des', models.TextField(max_length=500)),
                ('applicants', models.ManyToManyField(blank=True, related_name='applied_jobs', to='user.Dev')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.hr')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_applied', models.BooleanField()),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='user.dev')),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company.job')),
            ],
        ),
    ]
