# Generated by Django 3.1.2 on 2020-10-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201014_0608'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='user.dev')),
                ('job_name', models.ManyToManyField(related_name='applications', to='company.Job')),
            ],
        ),
    ]
