# Generated by Django 3.1.2 on 2020-10-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201029_1332'),
        ('company', '0003_auto_20201030_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.hr')),
                ('works_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
            ],
        ),
    ]
