# Generated by Django 3.1.2 on 2020-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='city',
            field=models.CharField(default='Kochi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
