# Generated by Django 3.1.2 on 2020-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201029_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_string',
            field=models.TextField(max_length=1000),
        ),
    ]
