# Generated by Django 3.1.2 on 2020-10-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201012_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DevBio',
            new_name='Bio',
        ),
    ]
