# Generated by Django 3.1.2 on 2020-11-07 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201031_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.dev')),
                ('vouched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='user.hr')),
            ],
        ),
    ]
