# Generated by Django 3.1.2 on 2020-11-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_vouch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchee', to='user.dev'),
        ),
    ]
